FROM osrf/ros:humble-desktop

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    python3-pip \
    python3-colcon-common-extensions \
    python3-opencv \
    git \
    ros-humble-navigation2 \
    ros-humble-nav2-bringup \
    ros-humble-slam-toolbox \
    ros-humble-gazebo-ros-pkgs \
    ros-humble-image-transport \
    ros-humble-cv-bridge \
    ros-humble-ros-gz \
    ros-humble-ros-gz-bridge \
    ros-humble-ros-gz-sim \
    && rm -rf /var/lib/apt/lists/*

RUN pip install \
    websockets \
    numpy==1.24.4

WORKDIR /ros_ws
COPY ros_ws /ros_ws

RUN /bin/bash -c "source /opt/ros/humble/setup.bash && colcon build"

COPY ros_ws/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]